/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AdminDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Messages`; params?: Router.UnknownInputParams; } | { pathname: `/Notifications`; params?: Router.UnknownInputParams; } | { pathname: `/RegisterScreen`; params?: Router.UnknownInputParams; } | { pathname: `/ResetPasswordScreen`; params?: Router.UnknownInputParams; } | { pathname: `/StartScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Camera` | `/Camera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Dashboard` | `/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Discover` | `/Discover`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Leaderboard` | `/Leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Map` | `/Map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/connections`; params?: Router.UnknownInputParams; } | { pathname: `/profile/[userId]`, params: Router.UnknownInputParams & { userId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/AdminDashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/Messages`; params?: Router.UnknownOutputParams; } | { pathname: `/Notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/RegisterScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/ResetPasswordScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/StartScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Camera` | `/Camera`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Dashboard` | `/Dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Discover` | `/Discover`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Leaderboard` | `/Leaderboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Map` | `/Map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/connections`; params?: Router.UnknownOutputParams; } | { pathname: `/profile/[userId]`, params: Router.UnknownOutputParams & { userId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/AdminDashboard${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/LoginScreen${`?${string}` | `#${string}` | ''}` | `/Messages${`?${string}` | `#${string}` | ''}` | `/Notifications${`?${string}` | `#${string}` | ''}` | `/RegisterScreen${`?${string}` | `#${string}` | ''}` | `/ResetPasswordScreen${`?${string}` | `#${string}` | ''}` | `/StartScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Camera${`?${string}` | `#${string}` | ''}` | `/Camera${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Dashboard${`?${string}` | `#${string}` | ''}` | `/Dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Discover${`?${string}` | `#${string}` | ''}` | `/Discover${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Leaderboard${`?${string}` | `#${string}` | ''}` | `/Leaderboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Map${`?${string}` | `#${string}` | ''}` | `/Map${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Profile${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | `/profile/connections${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/AdminDashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/Messages`; params?: Router.UnknownInputParams; } | { pathname: `/Notifications`; params?: Router.UnknownInputParams; } | { pathname: `/RegisterScreen`; params?: Router.UnknownInputParams; } | { pathname: `/ResetPasswordScreen`; params?: Router.UnknownInputParams; } | { pathname: `/StartScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Camera` | `/Camera`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Dashboard` | `/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Discover` | `/Discover`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Leaderboard` | `/Leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Map` | `/Map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `/profile/connections`; params?: Router.UnknownInputParams; } | `/profile/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/profile/[userId]`, params: Router.UnknownInputParams & { userId: string | number; } };
    }
  }
}
